name 'mimic'
maintainer 'reach-qe'
maintainer_email 'reach-qe@rackspace.com'
license 'All rights reserved'
description 'Installs and Starts Mimic'
long_description 'Installs mimic using a virtualenv and starts it on port 8900'
version '0.1.0'

depends 'apt'
depends 'python'
